version: '3'
services:
  postgres-db:
    image: 'postgres:10'
    container_name: 'java_postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=postgres'

  app:
    build: ./
    container_name: 'java_app'
    ports:
      - '8085:8085'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres'